<?php

namespace App\Model\Table;

use Cake\ORM\Table;

class ArticlesTable extends Table
{
    public function initialize(array $config)
    {
        parent::initialize($config); // TODO: Change the autogenerated stub
        $this->belongsTo('Categs');
        $this->belongsTo('Emplacements');
        $this->belongsToMany('Fournisseurs');
    }
}
