<?php

namespace App\Model\Table;

use Cake\ORM\Table;

class CategsTable extends Table
{
    public function initialize(array $config)
    {
        parent::initialize($config); // TODO: Change the autogenerated stub
        $this->hasMany('Articles');
    }
}
